[package]
name = "code_stats"
version = "0.1.0"
authors = ["subamanis <petrospapa21@gmail.com>"]
edition = "2018"

[dependencies]
colored = "2"
lazy_static = "1.4.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench_parsing"
harness = false